server:
  port: 9090
  servlet:
    contextPath: /hello-consumer

eureka: 
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://server1:8761/eureka/
#,http://server2:8762/eureka/,http://server3:8763/eureka/